const app = document.querySelector('#app');
app.innerHTML = `
<header><div class="brand"><span class="mark">P</span><div><b>PillCount</b><small>Pharmacy counter - MVP</small></div></div><button id="help" class="icon" aria-label="About PillCount">?</button></header>
<main><section class="card hero"><div><span class="eyebrow">FAST, LOCAL, PRIVATE</span><h1>Count pills with confidence.</h1><p>Upload a tray photo or use your Android rear camera. Review every detection before saving.</p><div class="actions"><label class="button primary">Capture / upload<input id="file" type="file" accept="image/*" capture="environment" hidden></label><button id="demo" class="button secondary">Try demo image</button></div><p id="secure" class="hint"></p></div></section>
<section class="card target"><div><span class="eyebrow">TARGET QUANTITY</span><h2>How many pills?</h2></div><div class="presets" role="group"><button data-target="30">30</button><button data-target="60">60</button><button data-target="90">90</button><button data-target="custom">Custom</button></div><input id="custom" type="number" min="1" max="9999" placeholder="Custom quantity" hidden></section>
<section class="card review"><div class="section-head"><div><span class="eyebrow">REVIEW</span><h2 id="status">Waiting for an image</h2></div><span id="countBadge" class="badge">0 detected</span></div><div id="stage" class="stage empty"><canvas id="canvas"></canvas><div class="empty-state"><span class="camera">+</span><b>Your photo appears here</b><small>Tap an empty area to add; tap a marker to remove</small></div><div id="zoom" class="zoom">100%</div></div><div class="toolbar"><button id="minus" class="round" aria-label="Remove one detection">-</button><strong id="count">0</strong><button id="plus" class="round" aria-label="Add one detection">+</button><span class="grow"></span><button id="undo" class="text">Undo</button><button id="redo" class="text">Redo</button></div><div class="actions"><button id="reanalyze" class="button secondary" disabled>Reanalyze</button><button id="save" class="button primary" disabled>Save correction</button></div></section>
<section class="card tips"><h2>Quick review</h2><div class="tip-grid"><span>1 <b>Bright light</b><small>Avoid glare and shadows</small></span><span>2 <b>Spread pills</b><small>Keep edges visible</small></span><span>3 <b>Zoom and inspect</b><small>Verify numbered markers</small></span></div><p id="notice" class="notice" hidden></p></section>
</main><footer>Local-first - No image is stored by default <a id="privacy">Privacy</a></footer>
<div id="modal" class="modal" hidden><div class="modal-box"><button id="close" class="close" aria-label="Close">x</button><h2>About PillCount</h2><p>This MVP detects bright, separated pill-like regions in your browser. Always verify the overlay; it is not a medical device.</p><p>Images stay in memory and are discarded on refresh. Only your final correction is saved locally in IndexedDB.</p></div></div>`;
const $=s=>document.querySelector(s); let target=30, image=null, detections=[], history=[], future=[], zoom=1;
const cvState={loaded:false};
let cvPromise;
const metrics={analyses:0,lastMs:0,lastDetector:'heuristic'};
function setStatus(){const n=detections.length; $('#count').textContent=n; $('#countBadge').textContent=`${n} detected`; const d=n-target; $('#status').textContent=!image?'Waiting for an image':d===0?'Match':d<0?`${Math.abs(d)} short`:`${d} over`; $('#status').className=d===0?'match':d<0?'short':'over';}
function draw(){const c=$('#canvas'),ctx=c.getContext('2d'); if(!image){$('#stage').classList.add('empty');return} $('#stage').classList.remove('empty'); const max=Math.min(900,innerWidth-40), scale=Math.min(max/image.width,500/image.height); c.width=image.width*scale; c.height=image.height*scale; ctx.drawImage(image,0,0,c.width,c.height); detections.forEach((d,i)=>{ctx.beginPath();ctx.arc(d.x*scale,d.y*scale,d.r*scale,0,Math.PI*2);ctx.fillStyle='rgba(27,185,148,.18)';ctx.fill();ctx.strokeStyle='#17b994';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#07251f';ctx.beginPath();ctx.arc(d.x*scale,d.y*scale,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 11px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(i+1,d.x*scale,d.y*scale)}); setStatus();}
function snapshot(){history.push(detections.map(x=>({...x}))); if(history.length>30)history.shift();future=[];}
function colorFallback(source){const c=document.createElement('canvas'),ctx=c.getContext('2d',{willReadFrequently:true});c.width=source.width;c.height=source.height;ctx.drawImage(source,0,0);const {data,width,height}=ctx.getImageData(0,0,c.width,c.height);const mask=new Uint8Array(width*height),seen=new Uint8Array(width*height),out=[];for(let i=0;i<mask.length;i++){const r=data[i*4],g=data[i*4+1],b=data[i*4+2],max=Math.max(r,g,b),min=Math.min(r,g,b);mask[i]=max>105&&max-min>24?1:0}for(let y=2;y<height-2;y++)for(let x=2;x<width-2;x++){const start=y*width+x;if(!mask[start]||seen[start])continue;const q=[start];seen[start]=1;let n=0,sx=0,sy=0,minX=x,maxX=x,minY=y,maxY=y;while(q.length){const p=q.pop(),px=p%width,py=(p-px)/width;n++;sx+=px;sy+=py;minX=Math.min(minX,px);maxX=Math.max(maxX,px);minY=Math.min(minY,py);maxY=Math.max(maxY,py);for(const np of [p-1,p+1,p-width,p+width])if(np>=0&&np<mask.length&&!seen[np]&&mask[np]){seen[np]=1;q.push(np)}}if(n>Math.max(80,width*height*.0003)&&n<width*height*.08){const r=Math.max(maxX-minX,maxY-minY)/2;out.push({x:sx/n,y:sy/n,r:Math.max(8,Math.min(80,r))})}}return out.filter((d,i,a)=>a.findIndex(x=>Math.hypot(x.x-d.x,x.y-d.y)<d.r*.7)===i).slice(0,100);}
function openCvDetect(source){const mat=cv.imread(source),rgb=new cv.Mat(),hsv=new cv.Mat(),mask=new cv.Mat(),contours=new cv.MatVector(),hierarchy=new cv.Mat();cv.cvtColor(mat,rgb,cv.COLOR_RGBA2RGB);cv.cvtColor(rgb,hsv,cv.COLOR_RGB2HSV);const low=new cv.Mat(hsv.rows,hsv.cols,hsv.type(),[0,28,75,0]),high=new cv.Mat(hsv.rows,hsv.cols,hsv.type(),[48,255,255,255]);cv.inRange(hsv,low,high,mask);const kernel=cv.getStructuringElement(cv.MORPH_ELLIPSE,new cv.Size(5,5));cv.morphologyEx(mask,mask,cv.MORPH_OPEN,kernel);cv.findContours(mask,contours,hierarchy,cv.RETR_EXTERNAL,cv.CHAIN_APPROX_SIMPLE);const minArea=Math.max(80,mat.cols*mat.rows*.00025),out=[];for(let i=0;i<contours.size();i++){const contour=contours.get(i),area=cv.contourArea(contour);if(area<minArea||area>mat.cols*mat.rows*.08){contour.delete();continue}const m=cv.moments(contour);if(!m.m00){contour.delete();continue}const rect=cv.boundingRect(contour);const r=Math.max(rect.width,rect.height)/2;out.push({x:m.m10/m.m00,y:m.m01/m.m00,r:Math.max(8,Math.min(80,r))});contour.delete()}mat.delete();rgb.delete();hsv.delete();mask.delete();contours.delete();hierarchy.delete();low.delete();high.delete();kernel.delete();return out;}
async function loadOpenCV(){if(cvState.loaded)return;if(cvPromise)return cvPromise;cvPromise=new Promise(resolve=>{const s=document.createElement('script');s.src='https://docs.opencv.org/4.x/opencv.js';s.async=true;s.onload=()=>{const ready=()=>{cvState.loaded=true;$('#notice').hidden=false;$('#notice').textContent='OpenCV.js ready. Reanalyze uses local color segmentation.';resolve()};if(window.cv&&cv.Mat)ready();else if(window.cv)cv.onRuntimeInitialized=ready;else resolve()};s.onerror=()=>resolve();document.head.appendChild(s)});return cvPromise}
const detector={async analyze(source){const started=performance.now();let result,detectorName;if(cvState.loaded){try{result=openCvDetect(source);detectorName='opencv-color-segmentation'}catch(error){result=colorFallback(source);detectorName='color-fallback'}}else{result=colorFallback(source);detectorName='color-fallback'}metrics.analyses++;metrics.lastMs=Math.round(performance.now()-started);metrics.lastDetector=detectorName;return result;}};
async function analyze(){if(!image)return;snapshot();await loadOpenCV();const started=performance.now();detections=detector.analyze(image);if(detections.then)detections=await detections;metrics.lastMs=Math.round(performance.now()-started);draw();$('#reanalyze').disabled=false;$('#save').disabled=false;}
function read(file){const url=URL.createObjectURL(file); const im=new Image(); im.onload=()=>{image=im; analyze(); URL.revokeObjectURL(url)}; im.src=url;}
function demo(){const c=document.createElement('canvas');c.width=900;c.height=600;const x=c.getContext('2d');x.fillStyle='#ded6c8';x.fillRect(0,0,c.width,c.height);for(let i=0;i<28;i++){const px=70+(i%7)*120,py=90+Math.floor(i/7)*120;x.fillStyle=i%2?'#e9eef4':'#f6c45e';x.beginPath();x.ellipse(px,py,30,22,(i%3)*.3,0,7);x.fill();x.strokeStyle='#9ba5b3';x.stroke()}const im=new Image();im.onload=()=>{image=im;analyze()};im.src=c.toDataURL()}
$('#file').onchange=e=>e.target.files[0]&&read(e.target.files[0]);$('#demo').onclick=demo;$('#reanalyze').onclick=analyze;
document.querySelectorAll('[data-target]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-target]').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.target==='custom'){$('#custom').hidden=false;$('#custom').focus()}else{target=+b.dataset.target;$('#custom').hidden=true;setStatus()}});$('#custom').oninput=e=>{target=Math.max(1,+e.target.value||1);setStatus()};
$('#plus').onclick=()=>{snapshot();detections.push({x:image?image.width/2:100,y:image?image.height/2:100,r:20});draw()};$('#minus').onclick=()=>{if(detections.length){snapshot();detections.pop();draw()}};$('#undo').onclick=()=>{if(history.length){future.push(detections);detections=history.pop();draw()}};$('#redo').onclick=()=>{if(future.length){history.push(detections);detections=future.pop();draw()}};
$('#save').onclick=async()=>{try{const db=await new Promise((res,rej)=>{const r=indexedDB.open('pillcount',1);r.onupgradeneeded=()=>r.result.createObjectStore('corrections',{autoIncrement:true});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});db.transaction('corrections','readwrite').objectStore('corrections').add({target,count:detections.length,at:new Date().toISOString()});$('#notice').hidden=false;$('#notice').textContent='Correction saved locally (image not stored).'}catch(e){$('#notice').hidden=false;$('#notice').textContent='Could not save locally in this browser.'}};
$('#stage').addEventListener('wheel',e=>{if(!image)return;e.preventDefault();zoom=Math.max(1,Math.min(2.5,zoom+(e.deltaY<0?.1:-.1)));$('#canvas').style.transform=`scale(${zoom})`;$('#zoom').textContent=`${Math.round(zoom*100)}%`},{passive:false});
$('#stage').addEventListener('dblclick',()=>{zoom=zoom===1?1.8:1;$('#canvas').style.transform=`scale(${zoom})`;$('#zoom').textContent=`${Math.round(zoom*100)}%`});
$('#stage').addEventListener('click',e=>{if(!image||e.target!==$('#canvas'))return;const rect=$('#canvas').getBoundingClientRect();const scale=$('#canvas').width/image.width;const x=(e.clientX-rect.left)/scale;const y=(e.clientY-rect.top)/scale;const hit=detections.findIndex(d=>Math.hypot(d.x-x,d.y-y)<Math.max(24,d.r*1.5));snapshot();if(hit>=0)detections.splice(hit,1);else detections.push({x,y,r:20});draw()});
$('#help').onclick=()=>$('#modal').hidden=false;$('#close').onclick=()=>$('#modal').hidden=true;$('#privacy').onclick=e=>{e.preventDefault();$('#modal').hidden=false};$('#secure').textContent=location.protocol==='https:'||location.hostname==='localhost'?'Camera-ready connection':'Camera requires HTTPS (or localhost).';loadOpenCV(); if('serviceWorker'in navigator)navigator.serviceWorker.register(new URL('sw.js',document.baseURI)).catch(()=>{});
